apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-logs
  labels:
    app.kubernetes.io/name: kube-state-logs
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-logs
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-state-logs
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: kube-state-logs
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: kube-state-logs
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          args:
            - --log-interval={{ .Values.config.logInterval }}
            - --resources={{ .Values.config.resources }}
            {{- if .Values.config.resourceConfigs }}
            - --resource-configs={{ .Values.config.resourceConfigs }}
            {{- end }}
            {{- if .Values.config.namespaces }}
            - --namespaces={{ .Values.config.namespaces }}
            {{- end }}
            - --log-level={{ .Values.config.logLevel }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
