apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-logs
  labels:
    app.kubernetes.io/name: kube-state-logs
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-logs
  labels:
    app.kubernetes.io/name: kube-state-logs
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
{{- if contains "deployments" .Values.config.resources }}
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
{{- end }}
{{- if contains "replicasets" .Values.config.resources }}
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
{{- end }}
{{- if contains "statefulsets" .Values.config.resources }}
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch"]
{{- end }}
{{- if contains "daemonsets" .Values.config.resources }}
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get", "list", "watch"]
{{- end }}
{{- if contains "pods" .Values.config.resources }}
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
{{- end }}
{{- if contains "services" .Values.config.resources }}
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
{{- end }}
{{- if contains "nodes" .Values.config.resources }}
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
{{- end }}
{{- if contains "namespaces" .Values.config.resources }}
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
{{- end }}
{{- if contains "jobs" .Values.config.resources }}
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
{{- end }}
{{- if contains "cronjobs" .Values.config.resources }}
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch"]
{{- end }}
{{- if contains "configmaps" .Values.config.resources }}
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
{{- end }}
{{- if contains "secrets" .Values.config.resources }}
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-state-logs
  labels:
    app.kubernetes.io/name: kube-state-logs
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-logs
subjects:
  - kind: ServiceAccount
    name: kube-state-logs
    namespace: {{ .Release.Namespace }} 