# Default values for kube-state-logs

# Image configuration
image:
  repository: kube-state-logs
  tag: "0.1.0"

# Application configuration
config:
  logInterval: "1m"
  resources:
    - pods
    - services
    - endpoints
    - nodes
    - deployments
    - jobs
    - cronjobs
    - configmaps
    - secrets
    - persistentvolumeclaims
    - persistentvolumes
    - resourcequotas
    - ingresses
    - horizontalpodautoscalers
    - serviceaccounts
  namespaces: ""
  logLevel: "info"

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi