# Default values for kube-state-logs

# Image configuration
image:
  repository: kube-state-logs
  tag: "0.1.0"

# Application configuration
config:
  logInterval: "1m"
  resources:
    - pod
    - service
    - node
    - deployment
    - job
    - cronjob
    - configmap
    - secret
    - persistentvolumeclaim
    - ingress
    - horizontalpodautoscaler
    - serviceaccount
    - endpoints
    - persistentvolume
    - resourcequota
    - poddisruptionbudget
    - storageclass
    - networkpolicy
    - replicationcontroller
    - limitrange
    - lease
    - role
    - clusterrole
    - rolebinding
    - clusterrolebinding
    - volumeattachment
    - certificatesigningrequest
  namespaces: ""
  logLevel: "info"

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi